import { Styles} from "styles.slint";
export component Mpris {
    Rectangle {
        background: #6EACDA;
        border-radius: 15px;
        min-height: 110px;

        HorizontalLayout {
            alignment: LayoutAlignment.stretch;
            padding: Styles.padding;

            Image {
                source: @image-url("../assets/nomusic.png");
                max-height: 80px;
            }

            VerticalLayout {
                Text {
                    font-size: 25px;
                    text: "Song Name";
                    TouchArea {
                        clicked => {
                        }
                    }
                }

                HorizontalLayout {
                    spacing: 10px;
                    Text {
                        font-size: 15px;
                        text: "Artist Name";
                    }

                    Text {
                        font-size: 15px;
                        text: "Artist Name";
                    }
                }

                HorizontalLayout {
                    spacing: 10px;
                    alignment: LayoutAlignment.space-between;

                    Rectangle {
                        padding: Styles.padding;
                        width: 10px;
                        border-radius: 15px;
                        background: #015B96;
                        Text {
                            text: "<";
                        }
                    }

                    Rectangle {
                        padding: Styles.padding;
                        width: 10px;
                        border-radius: 15px;
                        background: #015B96;
                        Text {
                            text: ">";
                        }
                    }

                    Rectangle {
                        padding: Styles.padding;
                        width: 10px;
                        border-radius: 15px;
                        background: #015B96;
                        Text {
                            text: "<";
                        }
                    }

                    Rectangle {
                        padding: Styles.padding;
                        width: 10px;
                        border-radius: 15px;
                        background: #015B96;
                        Text {
                            text: "<";
                        }
                    }
                }
            }
        }
    }
}
