import { Styles } from "styles.slint";
export component MyButton {
    width: mytext.width + (Styles.margin * 2);
    height: mytext.height + (Styles.margin * 2);
    in property <string> label;
    callback clicked();
    Rectangle {
        background: Styles.fun-gradient;
        // border-radius: 7px;
        mytext := Text {
            text: label;
            font-size: 30px;
            font-weight: 800;
        }

        TouchArea {
            clicked => {
                root.clicked();
            }
        }
    }
}
