import {
    Button,
    VerticalBox,
    Palette,
    Slider,
    Spinner,
    HorizontalBox,
    TabWidget,
    LineEdit,
    ScrollView,
} from "std-widgets.slint";
import {
    UButton,
    UDivider,
    UButton,
    UIconButton,
    UText,
    UIcon,
    ULinearProgress,
    UCard,
    USlider,
} from "@sleek/widgets.slint";
import { UAppTheme } from "@sleek/app-theme.slint";
import { Styles } from "styles.slint";
import { Mpris } from "mpris.slint";
import { WallpaperManager } from "wallpaper.slint";
import {
    PowerMenuButton,
    MenuButton,
    GeneralButton,
    SearchButton,
    AppDisplayButton,
    WorkspaceButton,
    BarButton,
} from "buttons.slint";
import { GeneralSlider, SystemInfo, AppViewer, GeneralCard } from "menu.slint";
import {
    AppLineData,
    Cards,
    State,
    SearchButtonData,
    BarState,
} from "data_structures.slint";
import { UTitle } from "@sleek/widgets/title.slint";
import { UCode } from "@sleek/widgets/code.slint";
import { USwitch } from "@sleek/widgets/switch.slint";
export { MprisState } from "mpris.slint";

export global MainState {
    in-out property <string> time;
    in-out property <string> date;
    in-out property <int> vol;
    in-out property <int> mic;
    in property <int> brightness;
    in property <percent> cpu;
    in property <percent> disk;
    pure callback get-time();
    pure callback get-date();
    pure callback get-volume();
    pure callback set-volume(int);
    pure callback get-mic();
    pure callback set-mic(int);
    pure callback get-bright();
    pure callback set-bright(int);
    pure callback get-disk();
    pure callback get-cpu();
    pure public function is-light-theme() -> bool {
        if Palette.color-scheme == ColorScheme.light {
            return true;
        } else {
            return false;
        }
    }
}

export component Menu inherits Window {
    out property <bool> first-run: true;
    property <int> volume <=> MainState.vol;
    property <int> mic <=> MainState.mic;
    property <int> bright <=> MainState.brightness;
    property <percent> cpu <=> MainState.cpu;
    property <percent> disk <=> MainState.disk;
    callback power-action(string);

    changed cpu => {
        cpu-bar.progress = self.cpu;
    }

    changed disk => {
        disk-bar.progress = self.disk;
    }
    changed mic => {
        mic-slider.value = self.mic;
    }
    changed volume => {
        vol-slider.value = self.volume;
    }
    changed bright => {
        bright-slider.value = self.bright;
    }
    width: 376px;
    height: 576px;
    background: transparent;
    public function set_dark_theme() {
        Palette.color-scheme = ColorScheme.dark;
    }
    public function set_light_theme() {
        Palette.color-scheme = ColorScheme.light;
    }

    Timer {
        running: true;
        interval: 1s;
        triggered => {
            MainState.get-time();
            MainState.get-volume();
            MainState.get-mic();
            MainState.get-bright();
            MainState.get-cpu();
            if first-run {
                first-run = false;
                MainState.get-date();
                MainState.get-disk();
            }
        }
    }

    Timer {
        running: true;
        interval: 3600s;
        triggered => {
            MainState.get-date();
            MainState.get-disk();
        }
    }

    Rectangle {
        clip: true;
        border-radius: UAppTheme.radius-medium;

        menu := Rectangle {
            width: parent.width - 50px;
            height: parent.height;
            background: UAppTheme.bg-container;
            x: 50px;
            y: 0px;
            VerticalLayout {
                padding: UAppTheme.padding-medium;
                spacing: UAppTheme.spacing-big;
                VerticalLayout {
                    UTitle {
                        text: "Hi Ramayen !";
                        vertical-alignment: TextVerticalAlignment.top;
                        height: 55px;
                    }

                    UDivider {
                        width: parent.width - 2 * UAppTheme.padding-medium;
                        height: 7px;
                        border-color: UAppTheme.bg-spotlight;
                    }
                }

                Rectangle {
                    height: 80px;
                    HorizontalLayout {
                        alignment: stretch;
                        padding: UAppTheme.padding-medium;
                        VerticalLayout {
                            spacing: UAppTheme.spacing-base;
                            alignment: start;
                            UText {
                                text: MainState.time;
                                font-size: UAppTheme.font-size-bigger;
                            }

                            UText {
                                text: MainState.date;
                                font-size: UAppTheme.font-size-bigger;
                            }
                        }

                        UButton {
                            width: 40px;
                            icon: @image-url("../assets/sleek/outlined/caret-right.svg");
                            icon-placement: start;
                        }
                    }
                }

                UCard {
                    height: 90px;
                    HorizontalLayout {
                        padding: UAppTheme.padding-medium;
                        spacing: UAppTheme.spacing-medium;
                        alignment: space-between;
                        GeneralCard {
                            switch: MainState.is_light_theme();
                            icon-on: @image-url("../assets/sleek/filled/bulb.svg");
                            icon-off: @image-url("../assets/sleek/outlined/bulb.svg");
                            on-open => {
                                root.set_dark_theme();
                            }
                            on-close => {
                                root.set_light_theme();
                            }
                        }

                        GeneralCard {
                            switch: false;
                            icon-on: @image-url("../assets/sleek/outlined/fullscreen.svg");
                            icon-off: @image-url("../assets/sleek/outlined/fullscreen-exit.svg");
                        }

                        GeneralCard {
                            switch: true;
                            icon-on: @image-url("../assets/sleek/outlined/zhihu.svg");
                            icon-off: @image-url("../assets/sleek/filled/zhihu-square.svg");
                        }

                        GeneralCard {
                            switch: true;
                            icon-on: @image-url("../assets/sleek/filled/wifi-signal-3.svg");
                            icon-off: @image-url("../assets/sleek/filled/wifi-slash.svg");
                        }

                        GeneralCard {
                            switch: false;
                            icon-on: @image-url("../assets/sleek/filled/bluetooth-on.svg");
                            icon-off: @image-url("../assets/sleek/filled/bluetooth-off.svg");
                        }
                    }
                }

                Mpris { }

                UCard {
                    width: parent.width - 2 * UAppTheme.spacing-medium;
                    VerticalLayout {
                        padding: UAppTheme.padding-big;
                        spacing: UAppTheme.spacing-big;
                        padding-left: UAppTheme.padding-big;
                        HorizontalLayout {
                            spacing: UAppTheme.spacing-bigger;
                            width: parent.width - 2 * UAppTheme.spacing-big;
                            height: 20px;
                            UIcon {
                                width: 25px;
                                image-fit: cover;
                                source: @image-url("../assets/sleek/filled/sound.svg");
                            }

                            vol-slider := USlider {
                                min-value: 0;
                                max-value: 120;
                                width: parent.width - 25px - 2 * UAppTheme.spacing-medium;
                                released(val) => {
                                    MainState.set-volume(val);
                                }
                            }
                        }

                        HorizontalLayout {
                            spacing: UAppTheme.spacing-bigger;
                            width: parent.width - 2 * UAppTheme.spacing-big;
                            height: 20px;
                            UIcon {
                                width: 25px;
                                image-fit: cover;
                                source: @image-url("../assets/sleek/filled/sun.svg");
                            }

                            bright-slider := USlider {
                                min-value: 0;
                                max-value: 100;
                                width: parent.width - 25px - 2 * UAppTheme.spacing-medium;
                                released(val) => {
                                    MainState.set-bright(val);
                                }
                            }
                        }

                        HorizontalLayout {
                            spacing: UAppTheme.spacing-bigger;
                            width: parent.width - 2 * UAppTheme.spacing-big;
                            height: 20px;
                            UIcon {
                                width: 25px;
                                image-fit: cover;
                                source: @image-url("../assets/sleek/outlined/mic-on.svg");
                            }

                            mic-slider := USlider {
                                min-value: 0;
                                max-value: 120;
                                width: parent.width - 25px - 2 * UAppTheme.spacing-medium;
                                released(val) => {
                                    MainState.set-mic(val);
                                }
                            }
                        }
                    }
                }

                UCard {
                    width: parent.width - 2 * UAppTheme.padding-medium;
                    VerticalLayout {
                        padding: UAppTheme.padding-medium;
                        alignment: space-between;
                        HorizontalLayout {
                            spacing: UAppTheme.spacing-medium;
                            UIcon {
                                vertical-alignment: ImageVerticalAlignment.top;
                                source: @image-url("../assets/sleek/filled/cpu.svg");
                            }

                            Rectangle {
                                width: parent.width - 2 * UAppTheme.padding-big;
                                cpu-bar := ULinearProgress {
                                    width: parent.width;
                                    progress: 50%;
                                }
                            }
                        }

                        HorizontalLayout {
                            spacing: UAppTheme.spacing-medium;
                            UIcon {
                                vertical-alignment: ImageVerticalAlignment.top;
                                source: @image-url("../assets/sleek/filled/disk.svg");
                            }

                            Rectangle {
                                width: parent.width - 2 * UAppTheme.padding-big;
                                disk-bar := ULinearProgress {
                                    width: parent.width;
                                    progress: 50%;
                                }
                            }
                        }
                    }
                }
            }
        }

        power-menu := Rectangle {
            x: 0px;
            background: UAppTheme.bg-spotlight;
            width: 50px;
            Rectangle {
                clip: true;
                y: UAppTheme.padding-medium;
                border-radius: UAppTheme.radius-medium;
                height: 50px;
                width: parent.width - 2 * UAppTheme.padding-medium;
                Image {
                    height: 50px;
                    source: @image-url("../assets/logo_dark.png");
                }
            }

            VerticalLayout {
                padding: UAppTheme.padding-medium;
                spacing: UAppTheme.spacing-medium;
                y: parent.height - (4 * self.width - 3 * UAppTheme.padding-medium);
                height: 4 * self.width - 3 * UAppTheme.padding-medium;
                UIconButton {
                    width: parent.width - (2 * UAppTheme.padding-medium);
                    height: self.width;
                    // (parent.height / 10) - (UAppTheme.padding-medium);
                    variant: primary;
                    icon: @image-url("../assets/sleek/outlined/poweroff.svg");
                    clicked => {
                        root.power-action("poweroff");
                    }
                }

                UIconButton {
                    width: parent.width - (2 * UAppTheme.padding-medium);
                    height: self.width;
                    // (parent.height / 10) - (UAppTheme.padding-medium);
                    variant: primary;
                    icon: @image-url("../assets/sleek/outlined/moon.svg");
                    clicked => {
                        root.power-action("sleep");
                    }
                }

                UIconButton {
                    width: parent.width - (2 * UAppTheme.padding-medium);
                    height: self.width;
                    // (parent.height / 10) - (UAppTheme.padding-medium);
                    variant: primary;
                    icon: @image-url("../assets/sleek/outlined/logout.svg");
                    clicked => {
                        root.power-action("logout");
                    }
                }

                UIconButton {
                    width: parent.width - (2 * UAppTheme.padding-medium);
                    height: self.width;
                    // (parent.height / 10) - (UAppTheme.padding-medium);
                    variant: primary;
                    icon: @image-url("../assets/sleek/outlined/lock.svg");
                    clicked => {
                        root.power-action("lock");
                    }
                }
            }
        }
    }
}

export component TopBar inherits Window {
    callback request-menu-toggle();
    callback walls_window_called();
    callback open-app(string);
    callback query-applications(string);
    callback set-wallpaper(image);
    in-out property <BarState> state: { is_search_on: false };
    in-out property <bool> walls_open: false;
    in property <[image]> walls_paths;
    in property <[image]> walls_light_paths;
    in property <[AppLineData]> app_lines: [];
    in property <[SearchButtonData]> topbar_buttons: [
        { text_val: "Apps", place_no: 1 },
        { text_val: "Clipboard", place_no: 2 },
        { text_val: "Wifi", place_no: 3 },
        { text_val: "Bluetooth", place_no: 4 },
        { text_val: "Walls", place_no: 5 },
        { text_val: "Color Picker", place_no: 6 },
        { text_val: "Emjois", place_no: 7 }
    ];

    in property <[length]> positions: [27px, 114px, 195px, 168px, 141px, 54px, 27px];
    in property <[length]> width-bar: [80px, 20px, 20px, 20px, 80px, 20px, 20px];
    in property <[string]> bar-text: [Rice.get_volume(), "", "h", "", "", "", ""];
    property <int> which-selected: 1;
    property <int> app_selected_no: 1;
    background: transparent;
    height: 610px;
    width: 1536px;

    Rectangle {
        x: 0px;
        y: 29px;
        height: 10px;
        background: transparent;
        Path {
            x: 7px;
            commands: "M 7 8 L 7 3 L 12 3 C 9 4 8 5 7 8";
            stroke: black;
            fill: black;
            width: 10px;
        }

        Path {
            x: 1538px;
            commands: "M 7 3 L 12 3 L 12 8 C 11 5 10 4 7 3";
            stroke: black;
            fill: black;
            width: 10px;
        }
    }

    Rectangle {
        clip: true;
        x: 0px;
        y: 0px;
        height: walls_open ? 350px : 30px;
        width: parent.width;
        background: Styles.dark-background;
        animate height { duration: 200ms; }

        WallpaperManager {
            walls_open: walls_open;
            walls_paths: walls_paths;
            walls_light_paths: walls_light_paths;
            switch-wallpapers(path) => {
                set-wallpaper(path);
            }
        }

        Rectangle {
            clip: true;
            y: 0px;
            background: black;
            height: 30px;

            Rectangle {
                x: 5px;
                width: 20px;
                background: Styles.dark-background;
                Image {
                    y: 7px;
                    width: 18px;
                    source: @image-url("../assets/icons/artixlinux.svg");
                    colorize: white;
                }

                TouchArea {
                    clicked => {
                        debug("Bar menu is opened or closed");
                        root.request-menu-toggle();
                        walls_open = false;
                        which-selected = 1;
                        if state.is_search_on {
                            state.is_search_on = false;
                            entryarea.clear-focus();
                        } else {
                            state.is_search_on = true;
                            entryarea.focus();
                            // entryarea.select-all();
                        }
                    }
                }
            }

            Rectangle {
                clip: true;
                x: 30px;
                y: state.is_search_on ? 0px : -42px;
                width: 495px;
                height: 30px;
                background: Styles.dark-background;
                entryarea := LineEdit {
                    y: 5px;
                    width: parent.width - 10px;
                    height: 20px;
                    x: 5px;
                    placeholder-text: "Search in " + topbar_buttons[which-selected - 1].text_val + "...";
                    edited(text) => {
                        root.query_applications(text)
                    }
                    key-pressed(event) => {
                        if event.text == Key.Escape {
                            root.request-menu-toggle();
                            walls_open = false;
                            which-selected = 1;
                            if state.is_search_on {
                                state.is_search_on = false;
                                entryarea.focus();
                            } else {
                                state.is_search_on = true;
                                entryarea.clear-focus();
                                entryarea.select-all();
                            }
                            accept;
                        } else if event.text == Key.RightArrow {
                            if which-selected < 7 {
                                which-selected += 1;
                                if which-selected == 5 {
                                    root.walls_window_called();
                                    walls_open = true;
                                } else {
                                    walls_open = false;
                                }
                            }
                            accept;
                        } else if event.text == Key.LeftArrow {
                            if which-selected > 1 {
                                which-selected -= 1;
                                if which-selected == 5 {
                                    root.walls_window_called();
                                    walls_open = true;
                                } else {
                                    walls_open = false;
                                }
                            }
                            accept;
                        } else if event.text == Key.UpArrow {
                            app_selected_no -= 1;
                            accept;
                        } else if event.text == Key.DownArrow {
                            app_selected_no += 1;
                            accept;
                        } else if event.text == "1" {
                            walls_open = false;
                            which-selected = 1;
                            walls_open = false;
                            accept;
                        } else if event.text == "2" {
                            walls_open = false;
                            if which-selected == 2 {
                                which-selected = 1;
                            } else {
                                which-selected = 2;
                            }
                            accept;
                        } else if event.text == "3" {
                            walls_open = false;
                            if which-selected == 3 {
                                which-selected = 1;
                            } else {
                                which-selected = 3;
                            }
                            accept;
                        } else if event.text == "4" {
                            walls_open = false;
                            if which-selected == 4 {
                                which-selected = 1;
                            } else {
                                which-selected = 4;
                            }
                            accept;
                        } else if event.text == "5" {
                            if which-selected == 5 {
                                which-selected = 1;
                                walls_open = false;
                            } else {
                                walls_open = true;
                                which-selected = 5;
                                // root.walls_window_called();
                            }
                            root.walls_window_called();
                            walls_open = true;
                            accept;
                        } else if event.text == "6" {
                            walls_open = false;
                            if which-selected == 6 {
                                which-selected = 1;
                            } else {
                                which-selected = 6;
                            }
                            accept;
                        } else if event.text == "7" {
                            walls_open = false;
                            if which-selected == 7 {
                                which-selected = 1;
                            } else {
                                which-selected = 7;
                            }
                            accept;
                        } else {
                            reject;
                        }
                    }
                }

                animate y {
                    easing: ease-in-out-back;
                    duration: 500ms;
                }
            }

            Rectangle {
                x: 535px;
                y: state.is_search_on ? 0px : -32px;
                width: root.width - 600px;
                HorizontalLayout {
                    padding: 4px;
                    spacing: 5px;
                    alignment: LayoutAlignment.stretch;
                    for action_button[i] in topbar_buttons: SearchButton {
                        is-selected: which-selected == action-button.place_no;
                        place_no: action-button.place_no;
                        text_value: action-button.text_val;
                        on-clicked => {
                            if action-button.text_val == "Walls" {
                                root.walls_window_called();
                                if walls_open {
                                    walls_open = false;
                                    which-selected = 1;
                                } else {
                                    walls_open = true;
                                    which-selected = 5;
                                }
                            } else {
                                if which-selected == action-button.place-no {
                                    which-selected = 1;
                                } else {
                                    walls_open = false;
                                    which-selected = action-button.place-no;
                                }
                            }
                        }
                    }
                }

                animate y {
                    easing: ease-out-back;
                    duration: 500ms;
                }
            }

            for width[i] in width-bar: BarButton {
                position: i == 0 || i == 1 ? (positions[i]) : parent.width - positions[i];
                is_search_on: state.is_search_on;
                button-width: width;
                display_text: bar-text[i];
                on_clicked => {
                    if i == 0 {
                        Rice.call_pavucontrol();
                    }
                }
            }

            Rectangle {
                background: clock.has-hover ? Styles.base-background : Styles.dark-background;
                x: state.is_search_on ? root.width - 65px : root.width / 2;
                y: -5px;
                width: 100px;
                border-radius: self.height / 2;
                Text {
                    y: 3px;
                    horizontal-alignment: TextHorizontalAlignment.center;
                    vertical-alignment: TextVerticalAlignment.center;
                    text: MainState.time;
                    color: Styles.font-color-light;
                    font-size: 20px;
                }

                animate x { duration: 200ms; }
                clock := TouchArea {
                    clicked => {
                    }
                }
            }
        }
    }

    AppViewer {
        border-width: 2px;
        border-color: Styles.border-color;
        walls_open: walls_open;
        is_search_on: state.is_search_on;
        app_lines: app_lines;
        current_window: which-selected;
        is_app_selected: app_selected_no;
        open-app(action) => {
            state.is_search_on = false;
            root.open-app(action)
        }
    }
}

export component HideWin inherits Window {
    callback request-hide();
    Text {
        horizontal-alignment: TextHorizontalAlignment.center;
        vertical-alignment: TextVerticalAlignment.center;
        text: "Hello";
    }

    TouchArea {
        clicked => {
            root.request-hide();
        }
    }
}

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    width: 376px;
    height: 576px;
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}

export component LockScreen inherits Window {
    in-out property <bool> is_lock_activated: false;
    in-out property <bool> lock_error: false;
    callback check-pass(string);
    callback request_time();
    callback verify_fingerprint();
    in-out property <string> time_var: "04:34";
    in-out property <string> time_ampm: "AP";
    in-out property <string> finger_verification_response;
    in-out property <bool> finger_again: true;
    in-out property <int> no_of_attempts: 0;

    Timer {
        interval: 2s;
        running: finger_again;
        triggered => {
            finger_again = false;
            verify_fingerprint();
        }
    }

    Timer {
        interval: 1s;
        running: true;
        triggered => {
            if no_of_attempts < 3 && !finger_again {
                no_of_attempts += 1;
                finger_again = true;
            } else {
                self.stop();
            }
        }
    }

    Timer {
        interval: 200ms;
        running: true;
        triggered => {
            request_time();
        }
    }

    Timer {
        interval: 2s;
        running: lock_error;
        triggered => {
            lock_error = false;
        }
    }

    Rectangle {
        width: parent.width;
        Image {
            width: parent.width;
            source: @image-url("../../../../assets/wallpapers/city lights/wallpaperflare.com_wallpaper(5).jpg");
            image-fit: cover;
        }

        TouchArea {
            clicked => {
                if is_lock_activated {
                    is_lock_activated = false;
                } else {
                    is_lock_activated = true;
                }
            }
        }
    }

    Rectangle {
        height: parent.height;
        x: is_lock_activated ? root.width - 350px : root.width;
        // x: root.width - 350px;
        // opacity: is_lock_activated ? 100 : 0;
        width: 350px;
        Image {
            height: parent.height;
            source: @image-url("../assets/frosted_glass_2.jpeg");
        }

        Rectangle {

            Text {
                x: 50px;
                y: 220px;
                vertical-alignment: TextVerticalAlignment.center;
                horizontal-alignment: TextHorizontalAlignment.center;
                color: Styles.font-color-light;
                font-size: 75px;
                font-family: "Source Code Pro";
                // font-family: "DS DIGI Orbitron-Regular";
                text: time_var;
            }

            Text {
                x: 275px;
                y: 258px;
                vertical-alignment: TextVerticalAlignment.center;
                horizontal-alignment: TextHorizontalAlignment.center;
                color: Styles.font-color-light;
                font-size: 35px;
                font-family: "Source Code Pro";
                text: time_ampm;
            }

            Text {
                y: 310px;
                vertical-alignment: TextVerticalAlignment.center;
                horizontal-alignment: TextHorizontalAlignment.center;
                color: Styles.font-color-light;
                font-size: 35px;
                font-family: "Source Code Pro";
                text: "Welcome Back!";
            }

            input := LineEdit {
                input-type: password;
                height: 37px;
                width: 260px;
                font-size: 20px;
                placeholder-text: " Enter Password";
                accepted(text) => {
                    root.check-pass(text);
                    self.text = "";
                }
                init => {
                    self.focus();
                }
            }

            Text {
                y: 410px;
                font-size: 25px;
                font-family: "Source Code Pro";
                text: "Incorrect Password";
                opacity: lock_error ? 100 : 0;
            }

            Text {
                y: 410px;
                font-size: 25px;
                font-family: "Source Code Pro";
                text: finger_verification_response;
                opacity: !finger_again ? 100 : 0;
            }

            Text {
                y: parent.height - 50px;
                font-size: 20px;
                color: pink;
                font-weight: 60;
                font-family: "Orbitron Variable";
                text: "Entering Terra Incognita Space !!";
            }
        }

        animate x {
            delay: 200ms;
            duration: 500ms;
            easing: ease-in-out-quad;
        }
    }
}

export component Workspaces inherits Window {
    in-out property <[bool]> is-filled: [false, false, false, false, false, false, false, false, false, false];
    in-out property <[bool]> is-active: [false, false, false, false, false, false, false, false, false, false];
    callback refresh-workspaces();
    callback refresh-vol();
    callback refresh-info();
    callback change_called(int);
    width: 7px;
    x: 0px;
    height: 830px;
    background: Styles.dark-background;

    Timer {
        interval: 300ms;
        triggered => {
            refresh-workspaces();
            refresh-vol();
        }
    }

    Timer {
        interval: 3s;
        triggered => {
            refresh-info();
        }
    }

    VerticalLayout {
        y: 0px;
        alignment: LayoutAlignment.space-evenly;
        height: parent.height;
        spacing: 4px;
        for i in 10: WorkspaceButton {
            sugg_int: (parent.height / 10) - 4px;
            is_filled: is-filled[i];
            is-active: is-active[i];
            change_called => {
                change_called(i)
            }
        }
    }
}
