import { Button, VerticalBox, Palette, Slider, Spinner, HorizontalBox, TabWidget, LineEdit, ScrollView } from "std-widgets.slint";
import { Styles } from "styles.slint";
import { Mpris} from "mpris.slint";
import { PowerMenuButton, MenuButton, GeneralButton, SearchButton, AppDisplayButton} from "buttons.slint";
import { GeneralSlider, SystemInfo} from "menu.slint";

struct AppLineData {
    image: image,
    name: string,
    action: string,
}

export enum Cards {hearts, diamonds, spade, yellow }

struct State {
    is-power-menu-open: bool,
    brush-type: brush,
    string-type: string,
    cards-type: Cards}

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}

export component Resize inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}

export component TextIssue inherits Window {
    in-out property <bool> is_search_on: true;
    width: 495px;
    height: 40px;
    Rectangle {
        width: 20px;
        height: 20px;
        x: 2px;
        background: red;
        TouchArea {
            clicked => {
                if is_search_on {
                    is_search_on = false;
                    entryarea.clear-focus();
                } else {
                    is_search_on = true;
                    entryarea.focus();
                }
            }
        }
    }

    Rectangle {
        x: 30px;
        // Comment the below line to see the error.
        y: is_search_on ? 0px : -42px;
        entryarea := LineEdit {
            y: 5px;
            width: parent.width;
            height: 25px;
        }

        animate y { duration: 500ms; }
    }
}

export component TopBar inherits Window {
    callback request-menu-toggle();
    callback walls_window_called();
    callback open-app(string);
    callback query-applications(string);
    in-out property <bool> is_search_on: false;
    in-out property <bool> walls_open: false;
    in property <[AppLineData]> app_lines: [
        // {
        //     name: "Disocrd",
        //     image: @image-url("/home/ramayen/assets/app_images/.icons/logseq.png")
        // },
        // {
        //     name: "Disocrd",
        //     image: @image-url("/home/ramayen/assets/app_images/.icons/logseq.png")
        // }
    ];
    property <int> which-selected: 1;
    background: transparent;
    height: 610px;
    width: 1366px;

    Rectangle {
        x: 0px;
        y: 34px;
        height: 10px;
        background: transparent;
        Path {
            x: 0px;
            commands: "M 7 8 L 7 3 L 12 3 C 9 4 8 5 7 8";
            stroke: black;
            fill: black;
            width: 10px;
        }

        Path {
            x: 1356px;
            commands: "M 7 3 L 12 3 L 12 8 C 11 5 10 4 7 3";
            stroke: black;
            fill: black;
            width: 10px;
        }
    }

    Rectangle {
        clip: true;
        x: 0px;
        y: 0px;
        height: walls_open ? 350px : 35px;
        width: 1366px;
        background: Styles.dark-background;
        animate height { duration: 200ms; }

        Rectangle {
            out property <bool> click_event: false;
            height: 350px - 35px;
            width: 1366px;
            y: walls_open ? 35px : 0px;
            background: click_event ? pink : black;
            Text {
                color: Styles.font-color-light;
                text: "Walls will come";
                font-size: 150px;
            }

            TouchArea {
                clicked => {
                    if click_event {
                        click_event = false;
                    } else {
                        click_event = true;
                    }
                }
            }

            animate y { duration: 200ms; }
        }

        Rectangle {
            clip: true;
            y: 0px;
            background: black;
            height: 35px;
            Rectangle {
                x: 5px;
                width: 20px;
                Image {
                    y: 7px;
                    width: 18px;
                    source: @image-url("../assets/icons/artixlinux.svg");
                    colorize: white;
                }

                TouchArea {
                    clicked => {
                        root.request-menu-toggle();
                        walls_open = false;
                        which-selected = 1;
                        if is_search_on {
                            is_search_on = false;
                            entryarea.focus();
                        } else {
                            is_search_on = true;
                            // entryarea.focus();
                            entryarea.clear-focus();
                            entryarea.select-all();
                            // entryarea.clear-selection();
                        }
                    }
                }
            }

            Rectangle {
                clip: true;
                x: 30px;
                y: is_search_on ? 0px/*(walls_open ? -225px : 0px)*/ : -42px;
                width: 495px;
                height: 35px;
                background: Styles.dark-background;
                entryarea := LineEdit {
                    y: 5px;
                    width: parent.width;
                    height: 25px;
                    x: 5px;
                    placeholder-text: "Search Apps..";
                    accepted(text) => {
                        root.query_applications(text)
                    }
                }

                animate y {
              // if walls_open easing: ease-in-out-back;
                easing: ease-in-out-back;
                    duration: 500ms;
                }
            }

            Rectangle {
                x: 535px;
                y: is_search_on ? 0px : -32px;
                width: root.width - 600px;
                HorizontalLayout {
                    padding: 4px;
                    spacing: 5px;
                    alignment: LayoutAlignment.stretch;
                    apps := SearchButton {
                        is-selected: which-selected == 1 ? true : false;
                        place_no: 1;
                        text_value: "Apps";
                        on-clicked => {
                            which-selected = 1;
                        }
                    }

                    clipboard := SearchButton {
                        is-selected: which-selected == 2 ? true : false;
                        place_no: 2;
                        text_value: "Clipboard";
                        on-clicked => {
                            which-selected = 2;
                        }
                    }

                    wifi := SearchButton {
                        is-selected: which-selected == 3 ? true : false;
                        place_no: 3;
                        text_value: "Wifi";
                        on-clicked => {
                            which-selected = 3;
                        }
                    }

                    blue := SearchButton {
                        is-selected: which-selected == 4 ? true : false;
                        place_no: 4;
                        text_value: "Bluetooth";
                        on-clicked => {
                            which-selected = 4;
                        }
                    }

                    walls := SearchButton {
                        is-selected: which-selected == 5 ? true : false;
                        place_no: 5;
                        text_value: "Walls";
                        on-clicked => {
                            root.walls_window_called();
                            if walls_open {
                                walls_open = false;
                                which-selected = 1;
                            } else {
                                walls_open = true;
                                which-selected = 5;
                            }
                        }
                    }

                    picker := SearchButton {
                        is-selected: which-selected == 6 ? true : false;
                        place_no: 6;
                        text_value: "Color Picker";
                        on-clicked => {
                            which-selected = 6;
                        }
                    }

                    emojis := SearchButton {
                        is-selected: which-selected == 7 ? true : false;
                        place_no: 7;
                        text_value: "Emojis";
                        on-clicked => {
                            which-selected = 7;
                        }
                    }
                }

                animate y {
                    easing: ease-out-back;
                    duration: 500ms;
                }
            }

            Text {
                x: is_search_on ? root.width - 57px : 683px;
                y: 3px;
                horizontal-alignment: TextHorizontalAlignment.center;
                vertical-alignment: TextVerticalAlignment.center;
                text: "04:16 PM";
                color: Styles.font-color-light;
                font-size: 20px;
                animate x, y { duration: 200ms; }
            }
        }
    }

    Rectangle {
        // y: 40px;
        y: is_search_on ? (walls_open ? -600px : 40px) : -600px;
        x: 30px;
        background: Styles.dark-background;
        width: 424px;
        height: 566px;
        border-radius: 10px;
        // opacity: is_search_on ? (walls_open ? 0 : 100) : 0;

        animate y { duration: 200ms; }

        ScrollView {
            x: 0px;
            width: 424px;
            viewport-width: 424px;
            VerticalLayout {
                padding: 10px;
                spacing: 10px;
                for line[i] in app_lines: AppDisplayButton {
                    image_path: line.image;
                    app_name: line.name;
                    open_app => {
                        is_search_on = false;
                        root.open-app(line.action)
                    }
                    // image_path: @image-url(line.image);
                }
            }
        }
    }
}

// export component AppDisplay inherits Window {
//     callback open-app(string);
//     width: 424px;
//     height: 576px;
//     background: transparent;
//     in property <[AppLineData]> app_lines: [
//         {
//             name: "Disocrd",
//             image: @image-url("/home/ramayen/assets/app_images/.icons/logseq.png")
//         },
//         {
//             name: "Disocrd",
//             image: @image-url("/home/ramayen/assets/app_images/.icons/logseq.png")
//         }
//     ];
//     Rectangle {
//         clip: true;
//         border-radius: 10px;
//         background: Styles.dark-background;
//         ScrollView {
//             x: 0px;
//             width: 424px;
//             viewport-width: 424px;
//             VerticalLayout {
//                 padding: 10px;
//                 spacing: 10px;
//                 for line[i] in app_lines: AppDisplayButton {
//                     image_path: line.image;
//                     app_name: line.name;
//                     open_app => {
//                         root.open-app(line.action)
//                     }
//                     // image_path: @image-url(line.image);
//                 }
//             }
//         }
//     }
// }

export component Menu inherits Window {
    width: 376px;
    height: 576px;
    background: transparent;
    default-font-family: "Urbanist-Regular";
    in-out property <State> state: { is-power-menu-open: false };
    callback request-hide();

    // property <bool> is-power-menu-open: state.is-power-menu-open;
    mainrec := Rectangle {
        background: Styles.dark-background;
        border-radius: 10px;
        clip: true;

        menu := VerticalLayout {
            x: 50px;
            y: 0px;
            width: root.width - 50px;
            padding: Styles.padding;
            alignment: LayoutAlignment.start;
            spacing: Styles.padding;

            Text {
                text: "Hello Ramayen !";
                color: Styles.font-color-light;
                font-size: 30px;
                font-family: "Urbanist-Bold";
            }

            Rectangle {
                HorizontalLayout {
                    VerticalLayout {
                        Text {
                            text: "07: 37: 46 PM ";
                            color: Styles.font-color-light;
                            font-size: 25px;
                        }

                        Text {
                            text: "Sunday, 11th May";
                            color: Styles.font-color-light;
                            font-size: 20px;
                        }
                    }

                    GeneralButton { }
                }
            }

            Rectangle {
                background: Styles.base-background;
                border-radius: 15px;
                border-width: 2px;
                border-color: Styles.border-color;
                HorizontalLayout {
                    alignment: LayoutAlignment.space-around;
                    padding: Styles.padding;
                    // spacing: 10px;
                    MenuButton {
                        icon: @image-url("../assets/icons/light-bulb.svg");
                    }

                    MenuButton {
                        icon: @image-url("../assets/icons/zen-on.svg");
                    }

                    MenuButton {
                        icon: @image-url("../assets/icons/font-question.svg");
                    }

                    MenuButton {
                        icon: @image-url("../assets/icons/wifi.svg");
                    }

                    MenuButton {
                        icon: @image-url("../assets/icons/bluetooth.svg");
                    }
                }
            }

            mpris := Mpris { }

            Rectangle {
                background: Styles.base-background;
                border-radius: 10px;
                border-width: 2px;
                border-color: Styles.border-color;
                VerticalLayout {
                    padding: Styles.padding;
                    spacing: Styles.padding;
                    GeneralSlider { }

                    GeneralSlider { }

                    GeneralSlider { }
                }
            }

            HorizontalLayout {
                SystemInfo {
                    info-name: "CPU Usage";
                }

                SystemInfo {
                    info-name: "Temp Usage";
                }
            }
        }

        power-menu := Rectangle {
            x: 0px;
            background: Styles.base-background;
            border-top-left-radius: 10px;
            border-bottom-left-radius: 10px;
            width: state.is-power-menu-open ? 200px : 50px;

            animate width { duration: 200ms; }

            VerticalLayout {
                max-width: power-menu.width;
                height: mainrec.height;
                x: 0px;
                alignment: LayoutAlignment.stretch;
                padding: Styles.padding;

                Rectangle {
                    x: 0px;
                    height: 40px;
                    width: 30px;
                    clip: true;
                    border-radius: 8px;
                    border-width: 4px;
                    border-color: Styles.border-color;
                    Image {
                        x: 0px;
                        y: 0px;
                        width: 30px;
                        height: 40px;
                        source: @image-url("../assets/logo_dark.png");
                    }
                }

                VerticalLayout {
                    alignment: LayoutAlignment.end;
                    spacing: Styles.padding;
                    PowerMenuButton {
                        icon: @image-url("../assets/icons/power.svg");

                        is-open: state.is-power-menu-open;
                        button-width: power-menu.width - 20px;
                        label: "Shutdown";
                        clicked => {
                            if state.is-power-menu-open {
                                state = { is-power-menu-open: false };
                            } else {
                                state.is-power-menu-open = true;
                            }
                        }
                    }

                    PowerMenuButton {
                        icon: @image-url("../assets/icons/suspend.svg");

                        is-open: state.is-power-menu-open;
                        button-width: power-menu.width - 20px;
                        label: "Suspend";
                        clicked => {
                            if state.is-power-menu-open {
                                state.is-power-menu-open = false;
                            } else {
                                state.is-power-menu-open = true;
                            }
                        }
                    }

                    PowerMenuButton {
                        icon: @image-url("../assets/icons/lock.svg");
                        is-open: state.is-power-menu-open;
                        button-width: power-menu.width - 20px;
                        label: "Lock Screen";
                        clicked => {
                            if state.is-power-menu-open {
                                state.is-power-menu-open = false;
                            } else {
                                state.is-power-menu-open = true;
                            }
                        }
                    }

                    PowerMenuButton {
                        icon: @image-url("../assets/icons/log-out.svg");
                        is-open: state.is-power-menu-open;
                        button-width: power-menu.width - 20px;
                        label: "Log Out";
                        clicked => {
                            if state.is-power-menu-open {
                                state.is-power-menu-open = false;
                            } else {
                                state.is-power-menu-open = true;
                            }
                        }
                    }

                    PowerMenuButton {
                        icon: @image-url("../assets/icons/chevron-right.svg");
                        icon-open: @image-url("../assets/icons/chevron-left.svg");
                        is-open: state.is-power-menu-open;
                        button-width: power-menu.width - 20px;
                        is-special: true;
                        clicked => {
                            if state.is-power-menu-open {
                                state.is-power-menu-open = false;
                            } else {
                                state.is-power-menu-open = true;
                            }
                        }
                    }
                }
            }
        }
    }
}

export component HideWin inherits Window {
    callback request-hide();
    Text {
        horizontal-alignment: TextHorizontalAlignment.center;
        vertical-alignment: TextVerticalAlignment.center;
        text: "Hello";
    }

    TouchArea {
        clicked => {
            root.request-hide();
        }
    }
}

export component ScrollEx inherits Window {
    height: 35px;
    width: 1366px;
    background: Styles.dark-background;
    Rectangle {
        x: 5px;
        width: 20px;
        Image {
            width: 18px;
            source: @image-url("../assets/icons/artixlinux.svg");
            colorize: white;
        }
    }

    Rectangle {
        x: 30px;
        y: 0px;
        width: 495px;
        background: Styles.dark-background;
        // border-radius: 10px;
        // clip: true;
        // background: pink;
        LineEdit {
            width: parent.width;
            height: 25px;
            x: 5px;
            placeholder-text: "Search Apps..";
        }

        animate y {
            easing: ease-in-out-back;
            duration: 500ms;
        }
    }

    Rectangle {
        x: 535px;
        y: 0px;
        width: root.width - 600px;
        // opacity: is_search_on ? 100 : 0;
        ScrollView {
            width: parent.width;
            viewport-width: 800px;
            HorizontalLayout {
                padding: 2px;
                spacing: 5px;
                alignment: LayoutAlignment.stretch;
                SearchButton {
                    place_no: 1;
                    text_value: "Apps";
                }

                SearchButton {
                    place_no: 2;
                    text_value: "Clipboard";
                }

                SearchButton {
                    place_no: 3;
                    text_value: "Wifi";
                }

                SearchButton {
                    place_no: 4;
                    text_value: "Bluetooth";
                }

                SearchButton {
                    place_no: 4;
                    text_value: "Walls";
                }

                SearchButton {
                    place_no: 4;
                    text_value: "Color Picker";
                }

                SearchButton {
                    place_no: 4;
                    text_value: "Emojis";
                }
            }
        }
    }

    Text {
        x: root.width - 57px;
        horizontal-alignment: TextHorizontalAlignment.center;
        vertical-alignment: TextVerticalAlignment.center;
        text: "04:16 PM";
        color: Styles.font-color-light;
    }
}

export component InputEx inherits Window {
    background: transparent;
    Rectangle {
        clip: true;
        x: 30px;
        width: 495px;
        height: 35px;
        background: Styles.dark-background;
              // border-radius: 10px;
              // clip: true;
              // background: pink;
                entryarea := LineEdit {
            y: 5px;
            width: parent.width;
            height: 25px;
            x: 5px;
            placeholder-text: "Search Apps..";
        }
    }
}
