import { Button, VerticalBox, Palette, Slider, Spinner, HorizontalBox, TabWidget, LineEdit, ScrollView } from "std-widgets.slint";
import { Styles } from "styles.slint";
import { Mpris} from "mpris.slint";

import { PowerMenuButton, MenuButton, GeneralButton, SearchButton} from "buttons.slint";
import { GeneralSlider, SystemInfo} from "menu.slint";

export enum Cards {hearts, diamonds, spade, yellow }

struct State {
    is-power-menu-open: bool,
    brush-type: brush,
    string-type: string,
    cards-type: Cards}

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}

export component TopBar inherits Window {
    callback request-menu-toggle();
    in-out property <bool> is_search_on: false;
    height: 35px;
    width: 1366px;
    background: Styles.dark-background;
    Rectangle {
        x: 5px;
        width: 20px;
        Image {
            width: 18px;
            source: @image-url("../assets/icons/artixlinux.svg");
            colorize: white;
        }

        TouchArea {
            clicked => {
                root.request-menu-toggle();
                if is_search_on {
                    is_search_on = false;
                } else {
                    is_search_on = true;
                }
            }
        }
    }

    Rectangle {
        x: 30px;
        y: is_search_on ? 0px : -30px;
        width: 495px;
        background: Styles.dark-background;
        // border-radius: 10px;
        // clip: true;
        // background: pink;
        LineEdit {
            width: parent.width;
            height: 25px;
            x: 5px;
            placeholder-text: "Search Apps..";
        }

        animate y {
            easing: ease-in-out-back;
            duration: 500ms;
        }
    }

    Rectangle {
        x: 535px;
        y: is_search_on ? 0px : -32px;
        width: root.width - 600px;
        // opacity: is_search_on ? 100 : 0;
            HorizontalLayout {
            padding: 2px;
            spacing: 5px;
            alignment: LayoutAlignment.stretch;
            SearchButton {
                place_no: 1;
                text_value: "Apps";
            }

            SearchButton {
                place_no: 2;
                text_value: "Clipboard";
            }

            SearchButton {
                place_no: 3;
                text_value: "Wifi";
            }

            SearchButton {
                place_no: 4;
                text_value: "Bluetooth";
            }

            SearchButton {
                place_no: 4;
                text_value: "Walls";
            }

            SearchButton {
                place_no: 4;
                text_value: "Color Picker";
            }

            SearchButton {
                place_no: 4;
                text_value: "Emojis";
            }
        }

        animate y {
            easing: ease-out-back;
            duration: 500ms;
        }
    }

    Text {
        x: is_search_on ? root.width - 57px : 683px;
        horizontal-alignment: TextHorizontalAlignment.center;
        vertical-alignment: TextVerticalAlignment.center;
        text: "04:16 PM";
        color: Styles.font-color-light;
        font-size: 20px;
        animate x { duration: 200ms; }
    }
}

export component Menu inherits Window {
    width: 376px;
    height: 576px;
    background: transparent;
    default-font-family: "Urbanist-Regular";
    in property <State> state: { is-power-menu-open: false };
    callback request-hide();

    property <bool> is-power-menu-open: state.is-power-menu-open;
    mainrec := Rectangle {
        background: Styles.dark-background;
        border-radius: 10px;
        clip: true;

        menu := VerticalLayout {
            x: 50px;
            y: 0px;
            width: root.width - 50px;
            padding: Styles.padding;
            alignment: LayoutAlignment.start;
            spacing: Styles.padding;

            Text {
                text: "Hello Ramayen !";
                color: Styles.font-color-light;
                font-size: 30px;
                font-family: "Urbanist-Bold";
            }

            Rectangle {
                HorizontalLayout {
                    VerticalLayout {
                        Text {
                            text: "07: 37: 46 PM ";
                            color: Styles.font-color-light;
                            font-size: 25px;
                        }

                        Text {
                            text: "Sunday, 11th May";
                            color: Styles.font-color-light;
                            font-size: 20px;
                        }
                    }

                    GeneralButton { }
                }
            }

            Rectangle {
                background: Styles.base-background;
                border-radius: 15px;
                border-width: 2px;
                border-color: Styles.border-color;
                HorizontalLayout {
                    alignment: LayoutAlignment.space-around;
                    padding: Styles.padding;
                    // spacing: 10px;
                    MenuButton {
                        icon: @image-url("../assets/icons/light-bulb.svg");
                    }

                    MenuButton {
                        icon: @image-url("../assets/icons/zen-on.svg");
                    }

                    MenuButton {
                        icon: @image-url("../assets/icons/font-question.svg");
                    }

                    MenuButton {
                        icon: @image-url("../assets/icons/wifi.svg");
                    }

                    MenuButton {
                        icon: @image-url("../assets/icons/bluetooth.svg");
                    }
                }
            }

            mpris := Mpris { }

            Rectangle {
                background: Styles.base-background;
                border-radius: 10px;
                border-width: 2px;
                border-color: Styles.border-color;
                VerticalLayout {
                    padding: Styles.padding;
                    spacing: Styles.padding;
                    GeneralSlider { }

                    GeneralSlider { }

                    GeneralSlider { }
                }
            }

            HorizontalLayout {
                SystemInfo {
                    info-name: "CPU Usage";
                }

                SystemInfo {
                    info-name: "Temp Usage";
                }
            }
        }

        power-menu := Rectangle {
            x: 0px;
            background: Styles.base-background;
            border-top-left-radius: 10px;
            border-bottom-left-radius: 10px;
            width: is-power-menu-open ? 200px : 50px;

            animate width { duration: 200ms; }

            VerticalLayout {
                max-width: power-menu.width;
                height: mainrec.height;
                x: 0px;
                alignment: LayoutAlignment.stretch;
                padding: Styles.padding;

                Rectangle {
                    x: 0px;
                    height: 40px;
                    width: 30px;
                    clip: true;
                    border-radius: 8px;
                    border-width: 4px;
                    border-color: Styles.border-color;
                    Image {
                        x: 0px;
                        y: 0px;
                        width: 30px;
                        height: 40px;
                        source: @image-url("../assets/logo_dark.png");
                    }
                }

                VerticalLayout {
                    alignment: LayoutAlignment.end;
                    spacing: Styles.padding;
                    PowerMenuButton {
                        icon: @image-url("../assets/icons/power.svg");

                        is-open: is-power-menu-open;
                        button-width: power-menu.width - 20px;
                        label: "Shutdown";
                        clicked => {
                            if is-power-menu-open {
                                is-power-menu-open = false;
                            } else {
                                is-power-menu-open = true;
                            }
                        }
                    }

                    PowerMenuButton {
                        icon: @image-url("../assets/icons/suspend.svg");

                        is-open: is-power-menu-open;
                        button-width: power-menu.width - 20px;
                        label: "Suspend";
                        clicked => {
                            if is-power-menu-open {
                                is-power-menu-open = false;
                            } else {
                                is-power-menu-open = true;
                            }
                        }
                    }

                    PowerMenuButton {
                        icon: @image-url("../assets/icons/lock.svg");
                        is-open: is-power-menu-open;
                        button-width: power-menu.width - 20px;
                        label: "Lock Screen";
                        clicked => {
                            if is-power-menu-open {
                                is-power-menu-open = false;
                            } else {
                                is-power-menu-open = true;
                            }
                        }
                    }

                    PowerMenuButton {
                        icon: @image-url("../assets/icons/log-out.svg");
                        is-open: is-power-menu-open;
                        button-width: power-menu.width - 20px;
                        label: "Log Out";
                        clicked => {
                            if is-power-menu-open {
                                is-power-menu-open = false;
                            } else {
                                is-power-menu-open = true;
                            }
                        }
                    }

                    PowerMenuButton {
                        icon: @image-url("../assets/icons/chevron-right.svg");
                        icon-open: @image-url("../assets/icons/chevron-left.svg");
                        is-open: is-power-menu-open;
                        button-width: power-menu.width - 20px;
                        is-special: true;
                        clicked => {
                            if is-power-menu-open {
                                is-power-menu-open = false;
                            } else {
                                is-power-menu-open = true;
                            }
                        }
                    }
                }
            }
        }
    }
}

export component HideWin inherits Window {
    callback request-hide();
    Text {
        horizontal-alignment: TextHorizontalAlignment.center;
        vertical-alignment: TextVerticalAlignment.center;
        text: "Hello";
    }

    TouchArea {
        clicked => {
            root.request-hide();
        }
    }
}

export component ScrollEx inherits Window {
    height: 35px;
    width: 1366px;
    background: Styles.dark-background;
    Rectangle {
        x: 5px;
        width: 20px;
        Image {
            width: 18px;
            source: @image-url("../assets/icons/artixlinux.svg");
            colorize: white;
        }
    }

    Rectangle {
        x: 30px;
        y: 0px;
        width: 495px;
        background: Styles.dark-background;
        // border-radius: 10px;
        // clip: true;
        // background: pink;
        LineEdit {
            width: parent.width;
            height: 25px;
            x: 5px;
            placeholder-text: "Search Apps..";
        }

        animate y {
            easing: ease-in-out-back;
            duration: 500ms;
        }
    }

    Rectangle {
        x: 535px;
        y: 0px;
        width: root.width - 600px;
        // opacity: is_search_on ? 100 : 0;
        ScrollView {
            width: parent.width;
            viewport-width: 800px;
            HorizontalLayout {
                padding: 2px;
                spacing: 5px;
                alignment: LayoutAlignment.stretch;
                SearchButton {
                    place_no: 1;
                    text_value: "Apps";
                }

                SearchButton {
                    place_no: 2;
                    text_value: "Clipboard";
                }

                SearchButton {
                    place_no: 3;
                    text_value: "Wifi";
                }

                SearchButton {
                    place_no: 4;
                    text_value: "Bluetooth";
                }

                SearchButton {
                    place_no: 4;
                    text_value: "Walls";
                }

                SearchButton {
                    place_no: 4;
                    text_value: "Color Picker";
                }

                SearchButton {
                    place_no: 4;
                    text_value: "Emojis";
                }
            }
        }
    }

    Text {
        x: root.width - 57px;
        horizontal-alignment: TextHorizontalAlignment.center;
        vertical-alignment: TextVerticalAlignment.center;
        text: "04:16 PM";
        color: Styles.font-color-light;
    }
}
