import { Spinner, Slider, ScrollView, VerticalBox } from "std-widgets.slint";
import { Styles } from "styles.slint";
import {
    AppLineData,
    WifiLineData,
    SelectedSection,
    ConnectionStatus,
} from "data_structures.slint";
import {
    UCard,
    USwitch,
    UIcon,
    UTitle,
    UDivider,
    ULinearProgress,
    UButton,
    UIconButton,
    UInput,
    UNotification,
} from "@sleek/widgets.slint";
import { UAppTheme } from "@sleek/app-theme.slint";
import { UText } from "@sleek/widgets/text.slint";
import { UScrollView } from "@sleek/widgets/scrollview.slint";
import { UDarkColors } from "@sleek/colors.slint";
import { UButtonThemes } from "@sleek/widgets/button/theme.slint";
import { UFloatingIconButton } from "@sleek/widgets/floating-icon-button.slint";
import { UPopover } from "@sleek/widgets/popover.slint";
import { URadio } from "@sleek/widgets/radio.slint";

component AppComponent inherits UScrollView {
    in property <[AppLineData]> app_lines;
    in property <int> selected-content;
    callback set-app(int);
    VerticalLayout {
        width: parent.width - 10px;
        x: 0px;
        padding: UAppTheme.padding-medium;
        spacing: UAppTheme.spacing-medium;
        padding-right: parent.scrollbar-area;
        for app[i] in app_lines: UCard {
            border-width: 10px;
            height: 40px;
            background: i == selected-content ? (handle.has-hover ? UAppTheme.bg-container : UAppTheme.bg-spotlight) : (handle.has-hover ? UAppTheme.bg-container : UAppTheme.bg-elevated);
            HorizontalLayout {
                padding: UAppTheme.padding-medium;
                spacing: UAppTheme.spacing-big;
                Rectangle {
                    width: self.height;
                    clip: true;
                    border-radius: UAppTheme.radius-circle;
                    Image {
                        width: parent.height;
                        image-fit: ImageFit.fill;
                        source: app.image;
                    }
                }

                UTitle {
                    level: 4;
                    vertical-alignment: center;
                    text: app.name;
                }
            }

            handle := TouchArea {
                clicked => {
                    set-app(i);
                }
            }

            animate background { duration: UAppTheme.animation-duration; }
        }
    }
}

component ClipComponent inherits UScrollView {
    in property <[string]> clip_lines;
    in property <int> selected-content;
    callback set-clip(int);
    VerticalLayout {
        width: parent.width - 10px;
        x: 0px;
        padding: UAppTheme.padding-medium;
        spacing: UAppTheme.spacing-medium;
        padding-right: parent.scrollbar-area;
        for clip[i] in clip_lines: UCard {
            height: 40px;
            background: clip-handle.has-hover ? UAppTheme.bg-layout : UAppTheme.bg-container;
            border-color: UAppTheme.border;
            border-width: i == selected-content ? UAppTheme.focus-border-width : 0px;
            UTitle {
                level: 4;
                x: UAppTheme.padding-medium;
                width: parent.width - UAppTheme.padding-medium;
                height: parent.height;
                vertical-alignment: center;
                horizontal-alignment: left;
                overflow: elide;
                text: clip;
            }

            clip-handle := TouchArea {
                clicked => {
                    set-clip(i);
                }
            }

            animate background { duration: UAppTheme.animation-duration; }
        }
    }
}

component WifiComponent inherits VerticalLayout {
    in property <int> connected-network;
    in property <[WifiLineData]> wifi_lines;
    in-out property <bool> wifi-on;
    callback escape-focus();
    callback connect-with(WifiLineData);
    padding: UAppTheme.padding-medium;
    spacing: UAppTheme.spacing-medium;
    alignment: stretch;
    UCard {
        height: 45px;
        HorizontalLayout {
            padding: UAppTheme.padding-medium;
            spacing: UAppTheme.spacing-big;
            alignment: stretch;
            if switch.checked && connected-network >= 0: HorizontalLayout {
                alignment: stretch;
                spacing: UAppTheme.spacing-big;

                Rectangle {
                    width: 20px;
                    height: parent.height;
                    ULinearProgress {
                        height: parent.height;
                        orientation: vertical;
                        progress: wifi_lines[connected-network].strength;
                    }
                }

                UText {
                    horizontal-alignment: left;
                    vertical-alignment: center;
                    text: wifi_lines[connected-network].name;
                }

                UButton {
                    width: 115px;
                    danger: true;
                    icon: @image-url("../assets/sleek/outlined/delete.svg");
                    icon-placement: end;
                    variant: filled;
                    text: "Disconnect";
                }
            }

            if switch.checked && connected-network < 0: UText {
                text: "Not Connected";
            }

            if !switch.checked: UText {
                vertical-alignment: center;
                text: "Wifi Off";
            }

            Rectangle {
                width: 45px;
                switch := USwitch {
                    checked: wifi-on;
                    toggled() => {
                        root.wifi-on = self.checked;
                    }
                }
            }
        }
    }

    Rectangle {
        height: 7px;
        UDivider {
            width: parent.width - 4 * UAppTheme.padding-medium;
        }
    }

    if !wifi-on:Rectangle {
        UIcon {
            width: 200px;
            height: 200px;
            image-fit: ImageFit.contain;
            source: @image-url("../assets/sleek/filled/wifi-slash.svg");
        }
    }

    if wifi-on: UScrollView {
        VerticalLayout {
            width: parent.width - 5px;
            x: 0px;
            spacing: UAppTheme.spacing-medium;
            for wifi[i] in wifi_lines: UCard {
                height: 45px;
                property <bool> ask-password: false;
                HorizontalLayout {
                    alignment: stretch;
                    spacing: UAppTheme.spacing-big;
                    padding: UAppTheme.padding-medium;

                    Rectangle {
                        width: 20px;
                        ULinearProgress {
                            height: parent.height;
                            orientation: vertical;
                            progress: wifi_lines[i].strength;
                        }
                    }

                    UText {
                        horizontal-alignment: left;
                        vertical-alignment: center;
                        overflow: elide;
                        text: wifi.name;
                    }

                    if wifi.connection-status == ConnectionStatus.Connected: UButton {
                        variant: filled;
                        width: 115px;
                        danger: true;
                        icon: @image-url("../assets/sleek/outlined/delete.svg");
                        icon-placement: end;
                        text: "Disconnect";
                    }

                    if ask-password: UInput {
                        width: 170px;
                        error: wifi.pass-error;
                        placeholder: "Password ...";
                        clearable: true;
                        input-type: password;
                        key-pressed(event) => {
                            if event.text == Key.Escape {
                                ask-password = false;
                                escape-focus();
                                accept;
                            } else {
                                reject;
                            }
                        }
                    }

                    if wifi.connection-status == ConnectionStatus.Known || wifi.connection-status == ConnectionStatus.Unknown: UButton {
                        loading: ask-password;
                        variant: filled;
                        width: 100px;
                        icon: @image-url("../assets/sleek/outlined/link.svg");
                        icon-placement: end;
                        text: "Connect";
                        clicked => {
                            if wifi.connection-status == ConnectionStatus.Unknown {
                                ask-password = true;
                            } else {
                                connect-with(wifi);
                            }
                        }
                    }

                    if wifi_lines[i].connection-status == ConnectionStatus.Known: UIconButton {
                        variant: filled;
                        danger: true;
                        width: self.height;
                        icon: @image-url("../assets/sleek/outlined/delete.svg");
                    }
                }
            }
        }
    }
}

export component OptionSection inherits Rectangle {
    x: 10px;
    border-bottom-left-radius: UAppTheme.radius-medium;
    border-bottom-right-radius: UAppTheme.radius-medium;
    background: UAppTheme.bg-container;
    in property <SelectedSection> selection;
    in property <[AppLineData]> app_lines;
    in property <[string]> clip_lines;
    in property <[WifiLineData]> wifi_lines;
    in-out property <bool> wifi-on;
    in-out property <int> selected-content: 0;
    in-out property <int> connected-network: -1;
    callback set-app(int);
    callback set-clip(int);
    callback connect-with(WifiLineData);
    callback escape-focus();
    changed selection => {
        self.selected-content = 0;
    }

    if selection == SelectedSection.Application: AppComponent {
        app_lines: app_lines;
        selected-content: selected-content;
        set-app(val) => {
            set-app(val)
        }
    }
    if selection == SelectedSection.Clipboard: ClipComponent {
        clip_lines: clip_lines;
        selected-content: selected-content;
        set-clip(val) => {
            set-clip(val)
        }
    }

    if selection == SelectedSection.Wifi: WifiComponent {
        connected-network: connected-network;
        wifi_lines: wifi_lines;
        wifi-on: wifi-on;
        escape-focus => {
            escape-focus();
        }
        connect-with(val) => {
            connect-with(val)
        }
    }

    if selection == SelectedSection.Bluetooth: UText {
        text: "Bluetooth selected";
    }

    if selection == SelectedSection.Emoji: UText {
        text: "Emoji selected";
    }
}

export component DisplayComponent inherits Rectangle {
    in property <string> time;
    in property <string> date;
    in property <int> vol;
    in property <int> mic;
    in property <percent> cpu;
    in property <percent> temp;
    in property <int> bright;
    in property <string> battery-val;
    property <bool> show-date: false;
    out property <bool> battery-text;
    in-out property <bool> is-inhibit;
    pure callback get-search-active() -> bool;
    callback toggle-search-active();
    callback select-wifi();
    callback select-bluetooth();
    callback toggle-inhibit(bool);
    callback bright-menu-focus();
    callback vol-menu-focus();
    y: get-search-active() ? 30px : 0px;
    background: UAppTheme.bg-container;

    Rectangle {
        x: 0px;
        HorizontalLayout {
            width: 30px;
            x: 0px;
            padding: UAppTheme.padding-small;
            spacing: UAppTheme.spacing-base;
            UCard {
                HorizontalLayout {
                    spacing: UAppTheme.spacing-small;
                    UText {
                        vertical-alignment: center;
                        text: vol + "%";
                    }

                    Rectangle {
                        height: parent.height;
                        width: self.height;
                        UIcon {
                            source: @image-url("../assets/sleek/filled/sound.svg");
                        }
                    }

                    UText {
                        vertical-alignment: center;
                        text: mic + "%";
                    }

                    Rectangle {
                        height: parent.height;
                        width: self.height;
                        UIcon {
                            source: @image-url("../assets/sleek/filled/mic.svg");
                        }
                    }
                }

                TouchArea {
                    mouse-cursor: pointer;
                    clicked => {
                        vol-menu-focus();
                    }
                }
            }

            UIconButton {
                width: self.height;
                variant: text;
                icon: @image-url("../assets/sleek/filled/wifi-signal-3.svg");
                clicked => {
                    toggle-search-active();
                    select-wifi();
                }
            }

            Rectangle {
                height: parent.height;
                width: self.height;
                UIconButton {
                    variant: text;
                    icon: @image-url("../assets/sleek/filled/bluetooth-on.svg");
                    clicked => {
                        toggle-search-active();
                        select-bluetooth();
                    }
                }
            }

            UIconButton {
                width: self.height;
                variant: text;
                icon: is-inhibit ? @image-url("../assets/sleek/outlined/eye.svg") : @image-url("../assets/sleek/outlined/eye-invisible.svg");
                clicked => {
                    is-inhibit = !is-inhibit;
                    toggle-inhibit(root.is-inhibit);
                }
            }
        }

        UCard {
            width: 20px;
            horizontal-stretch: 0;
            x: (parent.width / 2) - (self.width / 2);
            UText {
                text: show-date ? date : time;
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    show-date = !show-date
                }
            }
        }

        HorizontalLayout {
            x: parent.width - self.preferred-width - UAppTheme.padding-medium;
            width: self.preferred-width;
            padding: UAppTheme.padding-small;
            spacing: UAppTheme.spacing-base;
            UIconButton {
                width: self.height;
                variant: text;
                icon: @image-url("../assets/sleek/outlined/apple.svg");
            }

            UIconButton {
                width: self.height;
                variant: text;
                icon: @image-url("../assets/sleek/outlined/thunderbolt.svg");
            }

            UCard {
                height: parent.height;
                HorizontalLayout {
                    spacing: UAppTheme.spacing-small;
                    ULinearProgress {
                        y: UAppTheme.padding-small;
                        orientation: vertical;
                        height: parent.height - 2 * UAppTheme.padding-small;
                        progress: cpu;
                    }

                    Rectangle {
                        height: parent.height;
                        width: self.height;
                        UIcon {
                            image-fit: ImageFit.cover;
                            source: @image-url("../assets/sleek/filled/cpu.svg");
                        }
                    }

                    ULinearProgress {
                        y: UAppTheme.padding-small;
                        orientation: vertical;
                        height: parent.height - 2 * UAppTheme.padding-small;
                        progress: temp;
                    }

                    Rectangle {
                        height: parent.height;
                        width: self.height;
                        UIcon {
                            source: @image-url("../assets/sleek/filled/temp.svg");
                        }
                    }
                }
            }

            UCard {
                height: parent.height;
                width: self.height;
                UIconButton {
                    height: parent.height - 5px;
                    width: self.height;
                    variant: text;
                    icon: @image-url("../assets/sleek/filled/circle-25.svg");
                    clicked => {
                        bright-menu-focus();
                    }
                }
            }

            UCard {
                width: battery-text ? 78px : self.height + 10px;
                height: parent.height;
                if !battery-text: UIcon {
                    width: self.height;
                    image-fit: cover;
                    source: @image-url("../assets/sleek/outlined/battery-half.svg");
                }
                if battery-text:  UText {
                    text: battery-val;
                }

                TouchArea {
                    mouse-cursor: pointer;
                    clicked => {
                        battery-text = !battery-text;
                    }
                }
            }

            UIconButton {
                width: self.height;
                variant: text;
                icon: @image-url("../assets/sleek/outlined/poweroff.svg");
            }
        }
    }

    animate y { duration: UAppTheme.animation-duration; }
}
