import { Styles } from "styles.slint";
export component PowerMenuButton inherits Rectangle {
    in property <image> icon;
    in property <image> icon-open;
    in property <string> label;
    in property <bool> is-open: false;
    in property <length> button-width: 30px;
    in property <bool> is-special: false;
    callback clicked();

    width: button-width;
    height: 40px;
    background: Styles.light-blue;
    border-radius: 10px;
    clip: true;

    // HorizontalLayout {
    //     padding: Styles.padding - 3px;
    //     width: root.width;
    //     alignment: LayoutAlignment.start;
    //     spacing: Styles.padding;

    label-text := Text {
        text: label;
        color: Styles.font-color-dark;
        font-family: "Urbanist-Bold";
        font-weight: 500;
        font-size: 23px;
        x: is-open ? 34px : -180px;
        vertical-alignment: TextVerticalAlignment.center;

        animate x { duration: 200ms; }
        // }
    }

    Rectangle {
        background: Styles.light-blue;
        x: 0px;
        width: is-special ? root.width : 30px;
        Image {
            x: is-special ? (is-open ? 75px : 5px) : 5px;
            width: 20px;
            source: is-special ? (is-open ? icon-open : icon) : icon;
            colorize: Styles.font-color-dark;
            animate x { duration: 200ms; }
        }
    }

    TouchArea {
        clicked => {
            root.clicked();
        }
    }
}

export component MenuButton {
    in property <image> icon;
    callback clicked();
    // width: menu.width - (root.width );
    width: 50px;
    height: 50px;
    Rectangle {
        border-radius: 20px;
        background: #AEEEEE;
        Image {
            width: root.width - 28px;
            source: icon;
        }

        TouchArea {
            clicked => {
                root.clicked();
            }
        }
    }
}

export component GeneralButton inherits Rectangle {
    in property <image> icon: @image-url("../assets/icons/chevron-right.svg");
    in property <length> button-width: 35px;
    in property <length> button-rad: 15px;
    background: #015B96;
    border-radius: button-rad;
    width: button-width;
    min-height: 30px;
    Image {
        width: 20px;
        source: icon;
        colorize: white;
    }

    TouchArea {
        clicked => {
        }
    }
}

export component AppDisplayButton inherits Rectangle {
    callback open_app();
    in property <image> image_path: @image-url("/home/ramayen/assets/app_images/.icons/logseq.png");
    in property <string> app_name: "Discord";
    height: 50px;
    border-width: 2px;
    border-radius: 15px;
    background: sensor.has-hover ? Styles.base-background : Styles.dark-background;
    border-color: Styles.border-color;
    HorizontalLayout {
        spacing: 20px;
        alignment: LayoutAlignment.start;
        padding: 9px;
        Image {
            y: 5px;
            height: 35px;
            width: 35px;
            source: image_path;
        }

        Text {
            vertical-alignment: TextVerticalAlignment.center;
            color: Styles.font-color-light;
            text: app_name;
            font-size: 25px;
        }
    }

    sensor := TouchArea {
        clicked => {
            root.open_app()
        }
    }
}

export component SearchButton inherits Rectangle {
    in-out property <int> place_no;
    in-out property <string> text_value: "Unknown";
    in property <bool> is-selected;
    callback on-clicked();
    border-radius: 10px;
    border-width: 2px;
    height: 27px;
    border-color: is-selected ? pink : Styles.border-color;
    background: is-selected ? Styles.pink-background : Styles.base-background;
    Text {
        x: 7px;
        y: 10px;
        horizontal-alignment: TextHorizontalAlignment.left;
        vertical-alignment: TextVerticalAlignment.bottom;
        text: place_no;
        font-size: 10px;
        color: is-selected ? pink : Styles.font-color-light;
    }

    Text {
        vertical-alignment: TextVerticalAlignment.center;
        text: text_value;
        color: is-selected ? pink : Styles.font-color-light;
    }

    animate border-width, border-color, background { duration: 150ms; }

    TouchArea {
        clicked => {
            root.on-clicked();
        }
    }
}
