import { Styles } from "styles.slint";
export component PowerMenuButton inherits Rectangle {
    in property <image> icon;
    in property <image> icon-open;
    in property <string> label;
    in property <bool> is-open: false;
    in property <length> button-width: 30px;
    in property <bool> is-special: false;
    callback clicked();

    width: button-width;
    height: 40px;
    background: Styles.light-blue;
    border-radius: 10px;
    clip: true;

    // HorizontalLayout {
    //     padding: Styles.padding - 3px;
    //     width: root.width;
    //     alignment: LayoutAlignment.start;
    //     spacing: Styles.padding;

    label-text := Text {
        text: label;
        color: Styles.font-color-dark;
        font-family: "Urbanist-Bold";
        font-weight: 500;
        font-size: 23px;
        x: is-open ? 34px : -180px;
        vertical-alignment: TextVerticalAlignment.center;

        animate x { duration: 200ms; }
        // }
    }

    Rectangle {
        background: Styles.light-blue;
        x: 0px;
        width: is-special ? root.width : 30px;
        Image {
            x: is-special ? (is-open ? 75px : 5px) : 5px;
            width: 20px;
            source: is-special ? (is-open ? icon-open : icon) : icon;
            colorize: Styles.font-color-dark;
            animate x { duration: 200ms; }
        }
    }

    TouchArea {
        clicked => {
            root.clicked();
        }
    }
}

export component MenuButton {
    in property <image> icon;
    callback clicked();
    // width: menu.width - (root.width );
    width: 50px;
    height: 50px;
    Rectangle {
        border-radius: 20px;
        background: #AEEEEE;
        Image {
            width: root.width - 28px;
            source: icon;
        }

        TouchArea {
            clicked => {
                root.clicked();
            }
        }
    }
}

export component GeneralButton inherits Rectangle {
    in property <image> icon: @image-url("../assets/icons/chevron-right.svg");
    in property <length> button-width: 35px;
    in property <length> button-rad: 15px;
    background: #015B96;
    border-radius: button-rad;
    width: button-width;
    min-height: 30px;
    Image {
        width: 20px;
        source: icon;
        colorize: white;
    }

    TouchArea {
        clicked => {
        }
    }
}

export component SearchButton inherits Window {
    in property <int> place_no;
    in property <string> text_value: "Unknown";
    Rectangle {
        y: root.y;
        border-radius: 10px;
        border-width: 2px;
        // min-width: 150px;
        height: 27px;
        border-color: Styles.border-color;
        background: Styles.base-background;
        Text {
            text: text_value;
            color: Styles.font-color-light;
        }
    }
}
