export enum MenuFocus {
    None,
    Volume,
    Mic,
    Brightness,
    Info,
    ActionPower,
    ActionSleep,
    ActionLock,
    ActionLogout,
}

export enum SelectedSection {
    Application,
    Clipboard,
    Wifi,
    Bluetooth,
    WallPaper,
    Emoji
}
export struct AppLineData {
    image: image,
    name: string,
    action: string,
}

export enum ConnectionStatus {
    Connected,
    Known,
    Unknown,
    Connecting,
}
export struct WifiLineData {
    name: string,
    strength: percent,
    pass-error: bool,
    connection-status: ConnectionStatus,
}

export struct SearchButtonData {
    text_val: string,
    place_no: int,
}

export enum Cards {hearts, diamonds, spade, yellow }

export struct BarState {
    is_search_on: bool,
}


export struct State {
    is-power-menu-open: bool,
    brush-type: brush,
    string-type: string,
    cards-type: Cards,
}
export struct NotifData {
    id      : int,
    id_rust : int,
    app-name: string,
    title   : string,
    subtitle: string,
    message : string,
    accent  : color,
    timeout : int,
    icon    : bool,
}
