export struct AppLineData {
    image: image,
    name: string,
    action: string,
}

export struct WifiLineData {
    name: string,
    strength: int,
    is-known: bool,
    is-connected: bool,
}

export struct SearchButtonData {
    text_val: string,
    place_no: int,
}

export enum Cards {hearts, diamonds, spade, yellow }

export struct BarState {
    is_search_on: bool}


export struct State {
    is-power-menu-open: bool,
    brush-type: brush,
    string-type: string,
    cards-type: Cards,
}


