
export enum SelectedSection {
    Application,
    Clipboard,
    Wifi,
    Bluetooth,
    WallPaper,
    Emoji
}
export struct AppLineData {
    image: image,
    name: string,
    action: string,
}

export enum ConnectionStatus {
    Connected,
    Known,
    Unknown,
    Connecting,
}
export struct WifiLineData {
    name: string,
    strength: percent,
    pass-error: bool,
    connection-status: ConnectionStatus,
}

export struct SearchButtonData {
    text_val: string,
    place_no: int,
}

export enum Cards {hearts, diamonds, spade, yellow }

export struct BarState {
    is_search_on: bool,
}


export struct State {
    is-power-menu-open: bool,
    brush-type: brush,
    string-type: string,
    cards-type: Cards,
}
