import { Spinner, Slider, ScrollView, VerticalBox } from "std-widgets.slint";
import { Styles } from "styles.slint";
import {
    AppLineData,
    WifiLineData,
    SelectedSection,
    ConnectionStatus,
} from "data_structures.slint";
import {
    UCard,
    USwitch,
    UIcon,
    UTitle,
    UDivider,
    ULinearProgress,
    UButton,
    UIconButton,
    UInput,
} from "@sleek/widgets.slint";
import { UAppTheme } from "@sleek/app-theme.slint";
import { UText } from "@sleek/widgets/text.slint";
import { UScrollView } from "@sleek/widgets/scrollview.slint";
import { UDarkColors } from "@sleek/colors.slint";
import { UButtonThemes } from "@sleek/widgets/button/theme.slint";

export component GeneralCard inherits UCard {
    in-out property <bool> switch:false;
    in property <image> icon-on;
    in property <image> icon-off;
    callback on-open();
    callback on-close();
    VerticalLayout {
        icon := UIcon {
            size: 50px;
            source: switch ? icon-on : icon-off;
        }

        Rectangle {
            USwitch {
                checked: switch;
            }
        }
    }

    TouchArea {
        clicked => {
            if switch {
                switch = false;
                root.on-open();
            } else {
                switch = true;
                root.on-close();
            }
        }
    }
}

// export component AppViewer inherits Rectangle {
//     in property <bool> walls_open;
//     in-out property <bool> is_search_on;
//     in property <[AppLineData]> app_lines;
//     in property <[WifiLineData]> blue_lines; //[
//     //     { name: "Hello friends", strength: 2, is-known:false },
//     //     { name: "Bluetooth 1", strength: 2, is-known:false },
//     //     { name: "Bluetooth 2", strength: 2, is-known:false },
//     //     { name: "Bluetooth 1", strength: 2, is-known:false },
//     //     { name: "Bluetooth 3", strength: 2, is-known:false },
//     //     { name: "Bluetooth 4", strength: 2, is-known:false },
//     //     { name: "Bluetooth 5", strength: 2, is-known:false },
//     //     { name: "Bluetooth 6", strength: 2, is-known:false },
//     //     { name: "Bluetooth 7", strength: 2, is-known:false },
//     //     { name: "Bluetooth 8", strength: 2, is-known:false },
//     //     { name: "Bluetooth 9", strength: 2, is-known:false },
//     //     { name: "Bluetooth: 10", strength: 2, is-known:false },
//     //     { name: "Bluetooth 11", strength: 2, is-known:false }
//     // ];
//     in property <[WifiLineData]> wifi_lines; //[
//     //     { name: "sdcsd", strength: 2, is-known:false },
//     //     { name: "Network 1", strength: 2, is-known:false },
//     //     { name: "Network 2", strength: 2, is-known:false },
//     //     { name: "Network 1", strength: 2, is-known:false },
//     //     { name: "Network 3", strength: 2, is-known:false },
//     //     { name: "Network 4", strength: 2, is-known:false },
//     //     { name: "Network 5", strength: 2, is-known:false },
//     //     { name: "Network 6", strength: 2, is-known:false },
//     //     { name: "Network 7", strength: 2, is-known:false },
//     //     { name: "Network 8", strength: 2, is-known:false },
//     //     { name: "Network 9", strength: 2, is-known:false },
//     //     { name: "Network: 10", strength: 2, is-known:false },
//     //     { name: "Network 11", strength: 2, is-known:false }
//     // ];
//     in property <[string]> clipboard_texts: [
//         "sdcsd",
//         "sdkkjsvcd",
//         "sdkkjsvcd",
//         "sdkkjsvcd",
//         "sdkkjsvcd",
//         "sdkkjsvcd",
//         "sdkkjsvcd",
//         "sdkkjsvcd",
//         "sdkkjsvcd",
//         "sdkkjsvcd",
//         "sdkkjsvcd"
//     ];
//     in property <int> is_app_selected: 1;
//     in property <int> current_window: 1;
//     in property <int> left_window: current_window + 1;
//     in property <int> right_window: current_window - 1;
//     callback open-app(string);
//     callback fetch-connections();
//     y: is_search_on ? (walls_open ? -600px : 40px) : -600px;
//     x: 30px;
//     background: Styles.dark-background;
//     width: 424px;
//     height: 566px;
//     clip: true;
//     border-radius: 10px;
//     animate y { duration: 200ms; }

//     Rectangle {
//         background: Styles.dark-background;
//         x: current_window == 1 ? 0px : (current_window > 1 ? - 424px : 424px);

//         Rectangle {
//             border-width: 2px;
//             width: parent.width;
//             border-color: pink;
//             height: 45px;
//         }

//         ScrollView {
//             x: 0px;
//             max-width: 424px;
//             viewport-width: 424px;
//             VerticalLayout {
//                 padding: 10px;
//                 spacing: 7px;
//                 for line[i] in app_lines: AppDisplayButton {
//                     is_app_selected: i == is_app_selected;
//                     image_path: line.image;
//                     app_name: line.name;
//                     open_app => {
//                         root.open-app(line.name)
//                     }
//                 }
//             }
//         }

//         animate x { duration: 200ms; }
//     }

//     Rectangle {
//         background: Styles.dark-background;
//         x: current_window == 2 ? 0px : (current_window > 2 ? - 424px : 424px);

//         ScrollView {
//             x: 0px;
//             max-width: 424px;
//             viewport-width: 424px;
//             VerticalLayout {
//                 padding: 10px;
//                 spacing: 10px;
//                 for clip[i] in clipboard_texts: ClipButton {
//                     name: clip;
//                     strength: i;
//                     copy => {
//                     }
//                 }
//             }
//         }

//         animate x { duration: 200ms; }
//     }

//     Rectangle {
//         background: Styles.dark-background;
//         x: current_window == 3 ? 0px : (current_window > 3 ? - 424px : 424px);

//         connected := WifiButtonConnected {
//             y: 10px;
//             width: parent.width - 20px;
//             x: 10px;
//             name: wifi_lines[0].name;
//             // strength: wifi_lines[0].strength;
//         }

//         Path {
//             y: connected.width-expanded ? 120px : 70px;
//             commands: "M 34 23 C 34 23 34 22 34 22 L 85 22 C 86 23 86 22 85 23 C 34 23 34 23 34 23";
//             width: parent.width - 20px;
//             height: 5px;
//             fill: Styles.border-color;
//             animate y { duration: 200ms; }
//         }

//         ScrollView {
//             x: 0px;
//             y: connected.width-expanded ? 130px : 80px;
//             width: 424px;
//             viewport-width: 424px;
//             height: connected.width-expanded ? parent.height - 130px : parent.height - 90px;
//             // viewport-height: connected.width-expanded ? parent.height - 130px : parent.height - 90px;
//             VerticalLayout {
//                 padding: 10px;
//                 spacing: 10px;
//                 for line[i] in wifi_lines: WifiButton {
//                     name: line.name;
//                     // strength: line.strength;
//                     strength: i + 1;
//                 }
//             }

//             animate y { duration: 200ms; }
//         }

//         animate x, width { duration: 200ms; }
//     }

//     Rectangle {
//         background: Styles.dark-background;
//         x: current_window == 4 ? 0px : (current_window > 4 ? - 424px : 424px);

//         blue_connected := BlueButtonConnected {
//             y: 10px;
//             width: parent.width - 20px;
//             x: 10px;
//             name: wifi_lines[0].name;
//             // strength: wifi_lines[0].strength;
//         }

//         Path {
//             y: connected.width-expanded ? 120px : 70px;
//             commands: "M 34 23 C 34 23 34 22 34 22 L 85 22 C 86 23 86 22 85 23 C 34 23 34 23 34 23";
//             width: parent.width - 20px;
//             height: 5px;
//             fill: Styles.border-color;
//             animate y { duration: 200ms; }
//         }

//         ScrollView {
//             x: 0px;
//             y: connected.width-expanded ? 130px : 80px;
//             width: 424px;
//             viewport-width: 424px;
//             height: connected.width-expanded ? parent.height - 130px : parent.height - 90px;
//             // viewport-height: connected.width-expanded ? parent.height - 130px : parent.height - 90px;
//             VerticalLayout {
//                 padding: 10px;
//                 spacing: 10px;
//                 for line[i] in blue_lines: BlueButton {
//                     name: line.name;
//                     // strength: line.strength;
//                     strength: i + 1;
//                 }
//             }

//             animate y { duration: 200ms; }
//         }

//         animate x { duration: 200ms; }
//     }

//     Rectangle {
//         background: Styles.dark-background;
//         x: current_window == 5 ? 0px : (current_window > 5 ? - 424px : 424px);
//         Text {
//             text: " Here Walls will come";
//             color: Styles.font-color-light;
//         }

//         animate x { duration: 200ms; }
//     }

//     Rectangle {
//         background: Styles.dark-background;
//         x: current_window == 6 ? 0px : (current_window > 6 ? - 424px : 424px);
//         Text {
//             text: " Here Color Picker will come";
//             color: Styles.font-color-light;
//         }

//         animate x { duration: 200ms; }
//     }

//     Rectangle {
//         background: Styles.dark-background;
//         x: current_window == 7 ? 0px : (current_window > 7 ? - 424px : 424px);
//         Text {
//             text: " Here Emoji will come";
//             color: Styles.font-color-light;
//         }

//         animate x { duration: 200ms; }
//     }
// }

    // export component TextIssue inherits Window {
//     in-out property <bool> is_search_on: true;
//     width: 495px;
//     height: 40px;
//     Rectangle {
//         width: 20px;
//         height: 20px;
//         x: 2px;
//         background: red;
//         TouchArea {
//             clicked => {
//                 if is_search_on {
//                     is_search_on = false;
//                     entryarea.clear-focus();
//                 } else {
//                     is_search_on = true;
//                     entryarea.focus();
//                 }
//             }
//         }
//     }
//
//     Rectangle {
//         x: 30px;
//         // Comment the below line to see the error.
//         y: is_search_on ? 0px : -42px;
//         entryarea := LineEdit {
//             y: 5px;
//             width: parent.width;
//             height: 25px;
//         }
//
//         animate y { duration: 500ms; }
//     }
// }
//
