import { Styles} from "styles.slint";
import { GeneralButton } from "buttons.slint";
export component Mpris {
    Rectangle {
        background: #6EACDA;
        border-radius: 15px;
        min-height: 110px;

        HorizontalLayout {
            alignment: LayoutAlignment.stretch;
            padding: Styles.padding;
            spacing: 15px;

            Image {
                source: @image-url("../assets/nomusic.png");
                max-height: 80px;
                TouchArea {
                    clicked => {
                    }
                }
            }

            VerticalLayout {
                Text {
                    font-size: 25px;
                    text: "Song Name";
                    TouchArea {
                        clicked => {
                        }
                    }
                }

                HorizontalLayout {
                    spacing: 10px;
                    Text {
                        font-size: 15px;
                        text: "Artist Name";
                    }

                    Text {
                        font-size: 15px;
                        text: "Artist Name";
                    }
                }

                HorizontalLayout {
                    spacing: 10px;
                    alignment: LayoutAlignment.space-between;
                    GeneralButton {
                        button-width: 30px;
                        icon: @image-url("../assets/mpris/skip-back.svg");
                        button-rad: 10px;
                    }

                    GeneralButton {
                        button-width: 30px;
                        icon: @image-url("../assets/mpris/replay-10-line.svg");
                        button-rad: 10px;
                    }

                    GeneralButton {
                        button-width: 30px;
                        icon: @image-url("../assets/mpris/play.svg");
                        button-rad: 10px;
                    }

                    GeneralButton {
                        button-width: 30px;
                        icon: @image-url("../assets/mpris/forward-10-line.svg");
                        button-rad: 10px;
                    }

                    GeneralButton {
                        button-width: 30px;
                        icon: @image-url("../assets/mpris/skip-forward.svg");
                        button-rad: 10px;
                    }
                }
            }
        }
    }
}
