import { Styles } from "styles.slint";
import { GeneralButton } from "buttons.slint";
import { UAppTheme } from "@sleek/app-theme.slint";
import { UText, UIconButton, UTitle } from "@sleek/widgets.slint";
import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { ULinearProgress } from "@sleek/widgets/linear-progress.slint";
import { UButton } from "@sleek/widgets/button/button.slint";

export global MprisState {
    in-out property <string> title: "NoTitle";
    in-out property <string> artist: "Unknown";
    in-out property <string> album: "Unknown";
    in-out property <image> song-poster: @image-url("../assets/nomusic.png");
    in-out property <image> song-poster-blur: @image-url("../assets/nomusic-blur.png");
    in-out property <percent> progress;
    in-out property <bool> first-run: true;
    pure callback refresh-mpris();
    pure callback forward();
    pure callback backward();
    pure callback prev-track();
    pure callback next-track();
    pure callback play-pause();
}

export component Mpris inherits Rectangle {
    border-radius: UAppTheme.radius-medium;
    height: 110px;
    clip: true;
    Timer {
        running: true;
        interval: 3s;
        triggered => {
            MprisState.refresh-mpris();
        }
    }

    Image {
        height: parent.height;
        image-fit: fill;
        source: MprisState.song-poster-blur;
    }

    VerticalLayout {
        spacing: UAppTheme.spacing-medium;
        padding: UAppTheme.padding-medium;
        HorizontalLayout {
            spacing: UAppTheme.spacing-big;
            alignment: start;
            Rectangle {
                clip: true;
                border-radius: UAppTheme.radius-large;
                width: root.height - 30px - 2 * UAppTheme.spacing-medium;
                Image {
                    width: root.height - 30px - 2 * UAppTheme.spacing-medium;
                    image-fit: cover;
                    source: MprisState.song-poster;
                }
            }

            VerticalLayout {
                width: 225px;
                spacing: UAppTheme.spacing-medium;
                UTitle {
                    level: 4;
                    // width: parent.width;
                    overflow: elide;
                    text: MprisState.title;
                    horizontal-alignment: center;
                }

                HorizontalLayout {
                    UText {
                        horizontal-alignment: center;
                        width: 90px;
                        overflow: elide;
                        text: MprisState.artist;
                    }

                    UText {
                        width: 90px;
                        overflow: elide;
                        text: MprisState.album;
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: space-between;
            horizontal-stretch: 1;
            spacing: UAppTheme.spacing-medium;
            UIconButton {
                variant: primary;
                icon: @image-url("../assets/sleek/filled/step-backward.svg");
            }

            UIconButton {
                icon: @image-url("../assets/sleek/outlined/left.svg");
            }

            UIconButton {
                icon: @image-url("../assets/sleek/filled/pause-circle.svg");
            }

            Rectangle {
                width: 120px;
                horizontal-stretch: 1;
                ULinearProgress {
                    width: parent.width;
                    progress: 40%;
                }
            }

            UIconButton {
                icon: @image-url("../assets/sleek/outlined/right.svg");
                clicked => {
                }
            }

            UIconButton {
                variant: primary;
                icon: @image-url("../assets/sleek/filled/step-forward.svg");
            }
        }
    }
}
