export global Styles {
    out property <length> padding: 10px;
    out property <brush> fun-gradient: @linear-gradient(90deg, rgba(42, 123, 155, 1) 0%, rgba(87, 199, 133, 1) 50%, rgba(237, 221, 83, 1) 100%);
    out property <color> dark-background: #000000;
    out property <color> base-background: #151218;
    out property <color> base-blue: #064273;
    out property <color> light-blue-a: #08528D;
    out property <color> light-blue: #8DCFEF;
    out property <color> light-blue-b: #095DA2;
    out property <color> light-blue-c: #0A6AB6;
    out property <color> light-blue-d: #156AB5;
    out property <color> dark-blue-a: #145EA8;
    out property <color> dark-blue-b: #11519A;
    out property <color> dark-blue-c: #0A3981;
    out property <color> dark-blue-d: #002F7E;
    out property <color> pink: #F3B5C3;
    out property <color> border-color: #B4B4B4;
    out property <color> font-color-light: #EBEBEB;
    out property <color> font-color-dark: #000000;

    out property <brush> border_brush: #001F3E.transparentize(0.6);
// #003DA3
// #0043B3
// #0030B3
//#E0DEF4
}
