
import { Styles } from "styles.slint";
import { ScrollView, TextEdit, VerticalBox } from "std-widgets.slint";
import { UAppTheme } from "@sleek/app-theme.slint";
import { UScrollView } from "@sleek/widgets/scrollview.slint";
export component WallpaperManager inherits Rectangle {
    in-out property <[image]> walls_paths;
    in-out property <[image]> walls_light_paths;
    out property <bool> dark-selected: true;
    callback switch-wallpapers(image);
    callback regain-focus();
    height: 350px - 30px;
    background: UAppTheme.bg-container;
    Rectangle {
        width: 30px;
        x: 10px;
        height: parent.height - 20px;
        border-radius: UAppTheme.radius-round;
        background: UAppTheme.bg-spotlight;
        Rectangle {
            y: dark-selected ? 0px : parent.height / 2;
            height: parent.height / 2;
            width: parent.width;
            background: UAppTheme.golden-purple.base;
            border-radius: UAppTheme.radius-round;
            animate y { duration: UAppTheme.animation-duration; }
            Text {
                transform-rotation: -90deg;
                text: dark-selected ? "Dark Themes" : "Light Themes";
            }

            TouchArea {
                clicked => {
                    dark-selected = !dark-selected;
                }
            }
        }
    }

    dark-scroll := UScrollView {
        x: 50px;
        width: parent.width - 50px;
        y: dark-selected ? 0px : parent.width;
        HorizontalLayout {
            height: parent.height - 20px;
            spacing: 10px;
            for path[i] in walls_paths: Rectangle {
                border-radius: 10px;
                clip: true;
                width: 400px;
                background: blue;
                border-width: 2px;
                border-color: Styles.border-color;
                Image {
                    height: sensor.has-hover ? parent.height + 12px : parent.height;
                    source: path;
                    animate height { duration: 200ms; }
                }

                Rectangle {
                    width: parent.width;
                    height: parent.height;
                    background: sensor.has-hover ? @linear-gradient(0deg, black 0%, transparent 40%, transparent 80%, black 100%) : transparent;
                    Text {
                        y: parent.height - 18px;
                        x: 10px;
                        text: "Image path";
                        color: sensor.has-hover ? white : transparent;
                        animate color { duration: 200ms; }
                    }
                }

                sensor := TouchArea {
                    clicked => {
                        switch-wallpapers(path);
                        regain-focus();
                    }
                }
            }
        }

        animate y { duration: 200ms; }
    }

    light-scroll := UScrollView {
        x: 50px;
        y: dark-selected ? -350px : 0px;
        width: parent.width - 50px;
        HorizontalLayout {
            height: parent.height - 20px;
            spacing: 10px;
            for path in walls_light_paths: Rectangle {
                border-radius: 10px;
                clip: true;
                width: 400px;
                background: pink;
                border-width: 2px;
                border-color: Styles.border-color;
                Image {
                    height: parent.height;
                    source: path;
                }

                TouchArea {
                    clicked => {
                        switch-wallpapers(path);
                        regain-focus();
                    }
                }
            }
        }

        animate y { duration: 200ms; }
    }

    animate y { duration: 200ms; }
}
