[package]
name = "young-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = { version = "1.8.0", features = [
  "raw-window-handle-06",
  "renderer-software",
] }
spell = { path = "../../spell/" }

[build-dependencies]
slint-build = "1.8.0"
